#!/bin/bash

# for restart_service
. /usr/local/eal4_testing/audit-test/utils/functions.bash || exit 2
. /usr/local/eal4_testing/audit-test/crypto/tests/tp_nss_functions.bash || exit 2

init() {
    nss_init $@
}

destroy() {
    nss_destroy $@
}

import() {
    local tmp= args="$@" rc=
    if [ "$2" = "-" ]; then
        tmp=$(mktemp) || return 1
        cat > "$tmp" || return 1
        args[1]="$tmp"
    fi
    nss_import $@; rc=$?
    [ "$tmp" ] && rm -f "$tmp"
    return $rc
}

case "$1" in
    init)    init ;;
    destroy) destroy ;;
    import)  import ;;
    *)       exit 1 ;;
esac

# vim: sts=4 sw=4 et :
