#!/bin/sh
AUTHSRV_DIR="/usr/local/eal4_testing/audit-test/utils/auth-server"

exit_error() {
    echo "Error: $@"
    exit 1
}

[ "$@" ] || exit_error "No hosts given"

# source ipa defaults
source $AUTHSRV_DIR/ipa_env 2>&1 || exit

# get kerberos ticket for IPA admin
echo $IPA_PASS | kinit ${IPA_ADMIN}@$IPA_REALM 2>&1 >/dev/null || \
    exit_error "Failed to get kerberos ticket for admin"

# add each given host
for HOST in "$@"; do
    STATUS="SKIP"

    # add host to IPA if needed
    if ! ipa host-show $HOST &>/dev/null; then
        ipa host-add --force $HOST 2>&1 || exit
        STATUS="OK"
    fi

    # get kerberos keytab for the host and prepare it for downloading
    if [ ! -f $IPA_DLDIR/${HOST}.keytab ]; then
        ipa-getkeytab -s $(hostname) -p host/$HOST -k $IPA_DLDIR/${HOST}.keytab 2>&1 || exit
        chown eal:eal $IPA_DLDIR/${HOST}.keytab 2>&1 || exit
        STATUS="OK"
    fi

    # set mapping of $IPA_STAFF user to staff_u:s0-s0:c0.c1023 for given host
    if ! ipa selinuxusermap-show | grep -q $HOST; then
        ipa selinuxusermap-add-host staff --hosts=$HOST >/dev/null
        STATUS="OK"
    fi

    echo $STATUS
done
