#!/bin/bash

# for restart_service
. /usr/local/eal4_testing/audit-test/utils/functions.bash || exit 2

confdir=/etc/ipsec.d

# unique toe-to-ns identifier
unique_id="audit-test-${REMOTE_ADDR}-to-${LOCAL_ADDR}"

reload_rules() {
    restart_service ipsec
}

create() {
    autoclean
    cat > "$confdir"/"$unique_id"."$1"
}
remove() {
    rm -f "$confdir"/"$unique_id"."$1"
}
autoclean() {
    # remove configs older than 3 days
    find "$confdir" -name "audit-test-*.*" -mmin +4320 -delete
}

case "$1" in
    secrets) create secrets ;;
    conf)    create conf ;;
    reload)  reload_rules ;;
    cleanup) remove secrets; remove conf ;;
             # don't reload on cleanup as it would require yet another
             # exclusive lock on the server + cleanup is done /automatically/
             # after some time
    *)       exit 1 ;;
esac

# vim: sts=4 sw=4 et :
