#! /usr/bin/expect -f
#*********************************************************************
#   Copyright (C) International Business Machines  Corp., 2000
#   Copyright (C) Hewlett-Packard Development Company, L.P., 2005
#
#   This program is free software;  you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY;  without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
#   the GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program;  if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
#  FILE   : ssh 
#
#  PURPOSE: Tests to see that ssh rejects an invalid password
#
#  SETUP: The program `/usr/bin/expect' MUST be installed.
#         The PASSWD and RHOST variables MUST be set prior to execution.
#
#  HISTORY:
#    03/03 Jerone Young (jeroney@us.ibm.com)
#    11/05 Adapted for failsafe pam_loginuid by Matt Anderson (mra@hp.com)
#
#
set RHOST $env(RHOST)
set TEST_USER $env(TEST_USER)
set TEST_USER_PASSWD $env(TEST_USER_PASSWD)

set timeout 90

#test invalid password

send_user "SSH Test Password \n"

spawn ssh -l $TEST_USER $RHOST whoami

while 1 {
	sleep 2 
	expect {

		"Are you sure you want to continue connecting (yes/no)?" { exp_send "yes\r"}
		"password:" {exp_send "$TEST_USER_PASSWD\r"}
		"$TEST_USER"  {
			send_user "SSH allowed $TEST_USER to login with his password, Test Passed \n"
			break
		}
	     "Connection reset by peer" {send_user "SSH did not allow $TEST_USER to login with his password\n"; exit 1}	
	}
	sleep 1
}

exit 0
