#!/bin/bash
###############################################################################
# (c) Copyright Hewlett-Packard Development Company, L.P., 2006
#
#   This program is free software;  you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY;  without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
#   the GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program;  if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
###############################################################################
#
# PURPOSE:
# Test the ability to filter based on a filesystem watch, including
# for events generated by a hard link or symlink to the watched location.

source filter_functions.bash || exit 2

# setup
watch=$tmp1

event_obj=$(get_event_obj $1)
[[ $event_obj != $watch ]] && prepend_cleanup "rm -f $event_obj"

auditctl -a exit,always -S open -F key=$watch -F path=$watch
prepend_cleanup "auditctl -d exit,always -S open -F key=$watch -F path=$watch"

log_mark="$(stat -c %s $audit_log)"

# test
do_open_file $event_obj

# verify audit record
augrok --seek=$log_mark "type=~SYSCALL" key==$watch \
    || exit_fail "Expected record not found."

exit_pass
