#!/bin/bash
###############################################################################
# (c) Copyright Hewlett-Packard Development Company, L.P., 2006
#
#   This program is free software;  you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY;  without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
#   the GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program;  if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
###############################################################################
#
# PURPOSE:
# Test the ability to filter based on a filesystem watch, including
# for events generated by a hard link or symlink to the watched location.
# Test kernel handling for open() of an existing file both with and without the
# O_CREAT flag.

source filter_functions.bash || exit 2

# setup
watch=$tmp1

event_obj=$(get_event_obj $1)
[[ $event_obj != $watch ]] && prepend_cleanup "rm -f $event_obj"

auditctl -a exit,always -S open -F key=$watch -F path=$watch
prepend_cleanup "auditctl -d exit,always -S open -F key=$watch -F path=$watch"

# use syscall utilities
PATH=$TOPDIR/utils:$TOPDIR/utils/bin:$PATH

# test open with O_CREAT|O_RDONLY; verify audit record
log_mark=$(stat -c %s $audit_log)
do_open $event_obj rdcr

augrok --seek=$log_mark type==SYSCALL key==$watch \
    || exit_fail "Expected record not found for open O_CREAT|O_RDONLY"

# test open with O_RDWR; verify audit record
log_mark=$(stat -c %s $audit_log)
do_open $event_obj rdwr

augrok --seek=$log_mark type==SYSCALL key==$watch \
    || exit_fail "Expected record not found for open O_RDWR"

exit_pass
