#!/bin/bash
# =============================================================================
# (c) Copyright Hewlett-Packard Development Company, L.P., 2005
# Written by Aron Griffis <aron@hp.com>
#
#   This program is free software;  you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY;  without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
#   the GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program;  if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
# =============================================================================
#
# PURPOSE:
# Verify ausearch finds requested records

export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
if [[ -z $TOPDIR ]]; then
    TOPDIR=$(
	while [[ ! $PWD -ef / ]]; do
	    [[ -f rules.mk ]] && { echo $PWD; exit 0; }
	    cd ..
	done
	exit 1
    ) || { echo "Can't find TOPDIR, where is rules.mk?" >&2; exit 2; }
    export TOPDIR
fi
PATH=$TOPDIR/utils:$PATH

source functions.bash

# some of these require sed -r, and all are compatible with it
collapse_interior_whitespace='s/[[:blank:]]+/ /g'
remove_trailing_whitespace='s/[[:blank:]]*$//'
remove_msg_space='s/(msg=audit[^)]*\)) :/\1:/'
remove_daemon_commas='/^type=DAEMON_START/s/,[[:blank:]]+/ /g'
[[ $* == *-i* ]] && remove_quotes='s/"//g' || remove_quotes=''

echo "# augrok --ausearch -if auditlog.sample $*" >&2
augrok_output=$(augrok --ausearch -if auditlog.sample "$@" \
    | sed -r "$collapse_interior_whitespace" \
    | sed -r "$remove_daemon_commas" \
    | sed -r "$remove_quotes" \
    | tee /dev/stderr \
    | sort)

if [[ -z $augrok_output ]]; then
    exit_error "augrok couldn't find anything"
fi

echo
echo "# ausearch -if auditlog.sample $*" >&2
ausearch_output=$(ausearch -if auditlog.sample "$@" \
    | sed -r "$collapse_interior_whitespace" \
    | sed -r "$remove_trailing_whitespace" \
    | sed -r "$remove_msg_space" \
    | sed -r "$remove_daemon_commas" \
    | sed -r "$remove_quotes" \
    | tee /dev/stderr \
    | sort)

echo
if [[ "$augrok_output" == "$ausearch_output" ]]; then
    exit_pass "output matches"
else
    echo "diff augrok_output ausearch_output"
    diff -u <(sed 's/[[:blank:]]/\n/g' <<<"$augrok_output") \
	    <(sed 's/[[:blank:]]/\n/g' <<<"$ausearch_output")
    echo
    exit_fail "discrepancies found"
fi
